fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
celon_software_common:
    resource: "@CelonSoftwareCommonBundle/Resources/config/routing.yml"
    prefix:   /

celon_software_admin:
    resource: "@CelonSoftwareAdminBundle/Resources/config/routing.yml"
    prefix:   /

