parameters:
#    celon_software_common.example.class: CelonSoftware\CommonBundle\Example

services:
#    celon_software_common.example:
#        class: %celon_software_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
